version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: web/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../input_PPT:/app/input_PPT
      - ../report_config.json:/app/report_config.json
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend